package Entities;
// Generated Sep 8, 2017 9:11:07 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * Class generated by hbm2java
 */
public class Class implements AbstractEntity, java.io.Serializable {

    private long classId;
    private LessonContent lessonContent;
    private Serializable code;
    private Date startDate;
    private Date endDate;
    private Serializable place;
    private Long teacherId;

    public Class() {
    }

    public Class(long classId) {
        this.classId = classId;
    }

    public Class(long classId, LessonContent lessonContent, Serializable code, Date startDate, Date endDate, Serializable place, Long teacherId) {
        this.classId = classId;
        this.lessonContent = lessonContent;
        this.code = code;
        this.startDate = startDate;
        this.endDate = endDate;
        this.place = place;
        this.teacherId = teacherId;
    }

    public long getClassId() {
        return this.classId;
    }

    public void setClassId(long classId) {
        this.classId = classId;
    }

    public LessonContent getLessonContent() {
        return this.lessonContent;
    }

    public void setLessonContent(LessonContent lessonContent) {
        this.lessonContent = lessonContent;
    }

    public Serializable getCode() {
        return this.code;
    }

    public void setCode(Serializable code) {
        this.code = code;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Serializable getPlace() {
        return this.place;
    }

    public void setPlace(Serializable place) {
        this.place = place;
    }

    public Long getTeacherId() {
        return this.teacherId;
    }

    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

}
