package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import Enums.ContentType;

/**
 * Content generated by hbm2java
 */
public class Content implements AbstractEntity, Serializable {

	private static final long serialVersionUID = 1L;
	private long contentId;
	private Content content;
	private String code;
	private String name;
	private ContentType type;
	private Integer durationInHours;
	private Boolean isParent;
	private String audioFilePath;
	private String pdfFilePath;
	private String lastModifiedBy;
	private Date creationDate;
	private String createdBy;
	private Date lastModifiedDate;
	private List<Content> contents = new ArrayList<>();

	public Content() {
	}

	public Content(long contentId) {
		this.contentId = contentId;
	}

	public long getContentId() {
		return this.contentId;
	}

	public void setContentId(long contentId) {
		this.contentId = contentId;
	}

	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public ContentType getType() {
		return this.type;
	}

	public void setType(ContentType type) {
		this.type = type;
	}

	public Integer getDurationInHours() {
		return this.durationInHours;
	}

	public void setDurationInHours(Integer durationInHours) {
		this.durationInHours = durationInHours;
	}

	public Boolean getIsParent() {
		return this.isParent;
	}

	public void setIsParent(Boolean isParent) {
		this.isParent = isParent;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public List<Content> getContents() {
		return contents;
	}

	public void setContents(List<Content> contents) {
		this.contents = contents;
	}

	public String getAudioFilePath() {
		return audioFilePath;
	}

	public void setAudioFilePath(String audioFilePath) {
		this.audioFilePath = audioFilePath;
	}

	public String getPdfFilePath() {
		return pdfFilePath;
	}

	public void setPdfFilePath(String pdfFilePath) {
		this.pdfFilePath = pdfFilePath;
	}

}
