package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * EducationalState generated by hbm2java
 */
public class EducationalState  implements java.io.Serializable {


     private long educationalStateId;
     private String code;
     private String name;
     private Set lessonContents = new HashSet(0);
     private Set stdStudents = new HashSet(0);

    public EducationalState() {
    }

	
    public EducationalState(long educationalStateId, String code) {
        this.educationalStateId = educationalStateId;
        this.code = code;
    }
    public EducationalState(long educationalStateId, String code, String name, Set lessonContents, Set stdStudents) {
       this.educationalStateId = educationalStateId;
       this.code = code;
       this.name = name;
       this.lessonContents = lessonContents;
       this.stdStudents = stdStudents;
    }
   
    public long getEducationalStateId() {
        return this.educationalStateId;
    }
    
    public void setEducationalStateId(long educationalStateId) {
        this.educationalStateId = educationalStateId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getLessonContents() {
        return this.lessonContents;
    }
    
    public void setLessonContents(Set lessonContents) {
        this.lessonContents = lessonContents;
    }
    public Set getStdStudents() {
        return this.stdStudents;
    }
    
    public void setStdStudents(Set stdStudents) {
        this.stdStudents = stdStudents;
    }




}


