package Entities;
// Generated Sep 8, 2017 9:11:07 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LessonContent generated by hbm2java
 */
public class LessonContent  implements java.io.Serializable {


     private long lessonContentId;
     private Content content;
     private Lesson lesson;
     private Long lessonContentId1;
     private Serializable code;
     private Date startDate;
     private Date endDate;
     private Serializable place;
     private Long teacherId;
     private String lastModifiedBy;
     private Date creationDate;
     private String createdBy;
     private Date lastModifiedDate;
     private Set classes = new HashSet(0);

    public LessonContent() {
    }

	
    public LessonContent(long lessonContentId) {
        this.lessonContentId = lessonContentId;
    }
    public LessonContent(long lessonContentId, Content content, Lesson lesson, Long lessonContentId1, Serializable code, Date startDate, Date endDate, Serializable place, Long teacherId, String lastModifiedBy, Date creationDate, String createdBy, Date lastModifiedDate, Set classes) {
       this.lessonContentId = lessonContentId;
       this.content = content;
       this.lesson = lesson;
       this.lessonContentId1 = lessonContentId1;
       this.code = code;
       this.startDate = startDate;
       this.endDate = endDate;
       this.place = place;
       this.teacherId = teacherId;
       this.lastModifiedBy = lastModifiedBy;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastModifiedDate = lastModifiedDate;
       this.classes = classes;
    }
   
    public long getLessonContentId() {
        return this.lessonContentId;
    }
    
    public void setLessonContentId(long lessonContentId) {
        this.lessonContentId = lessonContentId;
    }
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    public Lesson getLesson() {
        return this.lesson;
    }
    
    public void setLesson(Lesson lesson) {
        this.lesson = lesson;
    }
    public Long getLessonContentId1() {
        return this.lessonContentId1;
    }
    
    public void setLessonContentId1(Long lessonContentId1) {
        this.lessonContentId1 = lessonContentId1;
    }
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Serializable getPlace() {
        return this.place;
    }
    
    public void setPlace(Serializable place) {
        this.place = place;
    }
    public Long getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public Set getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set classes) {
        this.classes = classes;
    }




}


