package Entities;
// Generated Sep 29, 2017 12:28:05 PM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * LessonContent generated by hbm2java
 */
public class LessonContent  implements java.io.Serializable {


     private long lessonContentId;
     private Content content;
     private EducationalState educationalState;
     private Lesson lesson;
     private Place place;
     private Teacher teacher;
     private Serializable code;
     private Date startDate;
     private Date endDate;
     private String lastModifiedBy;
     private Date creationDate;
     private String createdBy;
     private Date lastModifiedDate;
     private Set classes = new HashSet(0);
     private Set studentLessonAttendences = new HashSet(0);

    public LessonContent() {
    }

	
    public LessonContent(long lessonContentId) {
        this.lessonContentId = lessonContentId;
    }
    public LessonContent(long lessonContentId, Content content, EducationalState educationalState, Lesson lesson, Place place, Teacher teacher, Serializable code, Date startDate, Date endDate, String lastModifiedBy, Date creationDate, String createdBy, Date lastModifiedDate, Set classes, Set studentLessonAttendences) {
       this.lessonContentId = lessonContentId;
       this.content = content;
       this.educationalState = educationalState;
       this.lesson = lesson;
       this.place = place;
       this.teacher = teacher;
       this.code = code;
       this.startDate = startDate;
       this.endDate = endDate;
       this.lastModifiedBy = lastModifiedBy;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastModifiedDate = lastModifiedDate;
       this.classes = classes;
       this.studentLessonAttendences = studentLessonAttendences;
    }
   
    public long getLessonContentId() {
        return this.lessonContentId;
    }
    
    public void setLessonContentId(long lessonContentId) {
        this.lessonContentId = lessonContentId;
    }
    public Content getContent() {
        return this.content;
    }
    
    public void setContent(Content content) {
        this.content = content;
    }
    public EducationalState getEducationalState() {
        return this.educationalState;
    }
    
    public void setEducationalState(EducationalState educationalState) {
        this.educationalState = educationalState;
    }
    public Lesson getLesson() {
        return this.lesson;
    }
    
    public void setLesson(Lesson lesson) {
        this.lesson = lesson;
    }
    public Place getPlace() {
        return this.place;
    }
    
    public void setPlace(Place place) {
        this.place = place;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }
    public Serializable getCode() {
        return this.code;
    }
    
    public void setCode(Serializable code) {
        this.code = code;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public Set getClasses() {
        return this.classes;
    }
    
    public void setClasses(Set classes) {
        this.classes = classes;
    }
    public Set getStudentLessonAttendences() {
        return this.studentLessonAttendences;
    }
    
    public void setStudentLessonAttendences(Set studentLessonAttendences) {
        this.studentLessonAttendences = studentLessonAttendences;
    }




}


