package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * LessonContent generated by hbm2java
 */
public class LessonContent implements AbstractEntity, Serializable {

	private static final long serialVersionUID = 1L;
	private long lessonContentId;
	private Content content;
	private EducationalState educationalState;
	private Lesson lesson;
	private Place place;
	private Teacher teacher;
	private String code;
	private Date startDate;
	private Date endDate;
	private String lastModifiedBy;
	private Date creationDate;
	private String createdBy;
	private Date lastModifiedDate;

	public LessonContent() {
	}

	public LessonContent(long lessonContentId) {
		this.lessonContentId = lessonContentId;
	}

	public long getLessonContentId() {
		return this.lessonContentId;
	}

	public void setLessonContentId(long lessonContentId) {
		this.lessonContentId = lessonContentId;
	}

	public Content getContent() {
		return this.content;
	}

	public void setContent(Content content) {
		this.content = content;
	}

	public EducationalState getEducationalState() {
		return this.educationalState;
	}

	public void setEducationalState(EducationalState educationalState) {
		this.educationalState = educationalState;
	}

	public Lesson getLesson() {
		return this.lesson;
	}

	public void setLesson(Lesson lesson) {
		this.lesson = lesson;
	}

	public Place getPlace() {
		return this.place;
	}

	public void setPlace(Place place) {
		this.place = place;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public Date getStartDate() {
		return this.startDate;
	}

	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	public Date getEndDate() {
		return this.endDate;
	}

	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	public String getLastModifiedBy() {
		return this.lastModifiedBy;
	}

	public void setLastModifiedBy(String lastModifiedBy) {
		this.lastModifiedBy = lastModifiedBy;
	}

	public Date getCreationDate() {
		return this.creationDate;
	}

	public void setCreationDate(Date creationDate) {
		this.creationDate = creationDate;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getLastModifiedDate() {
		return this.lastModifiedDate;
	}

	public void setLastModifiedDate(Date lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}

	public Teacher getTeacher() {
		return teacher;
	}

	public void setTeacher(Teacher teacher) {
		this.teacher = teacher;
	}

}
