package Entities;
// Generated Sep 29, 2017 12:28:05 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Level generated by hbm2java
 */
public class Level implements AbstractEntity, Serializable {

    private long levelId;
    private String code;
    private String title;
    private Date creationDate;
    private String createdBy;
    private Date lastModifiedDate;
    private String lastModifiedBy;
    private Set terms = new HashSet(0);

    public Level() {
    }

    public Level(long levelId) {
        this.levelId = levelId;
    }

    public Level(long levelId, String code, String title, Date creationDate, String createdBy, Date lastModifiedDate, String lastModifiedBy, Set terms) {
        this.levelId = levelId;
        this.code = code;
        this.title = title;
        this.creationDate = creationDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.terms = terms;
    }

    public long getLevelId() {
        return this.levelId;
    }

    public void setLevelId(long levelId) {
        this.levelId = levelId;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Set getTerms() {
        return this.terms;
    }

    public void setTerms(Set terms) {
        this.terms = terms;
    }

}
