package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1



/**
 * SetRolesNotification generated by hbm2java
 */
public class SetRolesNotification  implements java.io.Serializable {


     private SetRolesNotificationId id;
     private SetNotifications setNotifications;
     private UsrRole usrRole;

    public SetRolesNotification() {
    }

	
    public SetRolesNotification(SetRolesNotificationId id) {
        this.id = id;
    }
    public SetRolesNotification(SetRolesNotificationId id, SetNotifications setNotifications, UsrRole usrRole) {
       this.id = id;
       this.setNotifications = setNotifications;
       this.usrRole = usrRole;
    }
   
    public SetRolesNotificationId getId() {
        return this.id;
    }
    
    public void setId(SetRolesNotificationId id) {
        this.id = id;
    }
    public SetNotifications getSetNotifications() {
        return this.setNotifications;
    }
    
    public void setSetNotifications(SetNotifications setNotifications) {
        this.setNotifications = setNotifications;
    }
    public UsrRole getUsrRole() {
        return this.usrRole;
    }
    
    public void setUsrRole(UsrRole usrRole) {
        this.usrRole = usrRole;
    }




}


