package Entities;
// Generated Sep 29, 2017 12:28:05 PM by Hibernate Tools 4.3.1



/**
 * SetRolesNotificationId generated by hbm2java
 */
public class SetRolesNotificationId  implements java.io.Serializable {


     private Long notificationId;
     private Long roleId;

    public SetRolesNotificationId() {
    }

    public SetRolesNotificationId(Long notificationId, Long roleId) {
       this.notificationId = notificationId;
       this.roleId = roleId;
    }
   
    public Long getNotificationId() {
        return this.notificationId;
    }
    
    public void setNotificationId(Long notificationId) {
        this.notificationId = notificationId;
    }
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SetRolesNotificationId) ) return false;
		 SetRolesNotificationId castOther = ( SetRolesNotificationId ) other; 
         
		 return ( (this.getNotificationId()==castOther.getNotificationId()) || ( this.getNotificationId()!=null && castOther.getNotificationId()!=null && this.getNotificationId().equals(castOther.getNotificationId()) ) )
 && ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNotificationId() == null ? 0 : this.getNotificationId().hashCode() );
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         return result;
   }   


}


