package Entities;
// Generated Sep 8, 2017 9:11:07 PM by Hibernate Tools 4.3.1



/**
 * StudentLevelStateId generated by hbm2java
 */
public class StudentLevelStateId  implements java.io.Serializable {


     private long levelId;
     private long studentId;

    public StudentLevelStateId() {
    }

    public StudentLevelStateId(long levelId, long studentId) {
       this.levelId = levelId;
       this.studentId = studentId;
    }
   
    public long getLevelId() {
        return this.levelId;
    }
    
    public void setLevelId(long levelId) {
        this.levelId = levelId;
    }
    public long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentLevelStateId) ) return false;
		 StudentLevelStateId castOther = ( StudentLevelStateId ) other; 
         
		 return (this.getLevelId()==castOther.getLevelId())
 && (this.getStudentId()==castOther.getStudentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getLevelId();
         result = 37 * result + (int) this.getStudentId();
         return result;
   }   


}


