package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1



/**
 * StudentLessonAttendenceId generated by hbm2java
 */
public class StudentLessonAttendenceId  implements java.io.Serializable {


     private long studentId;
     private long lessonContentId;

    public StudentLessonAttendenceId() {
    }

    public StudentLessonAttendenceId(long studentId, long lessonContentId) {
       this.studentId = studentId;
       this.lessonContentId = lessonContentId;
    }
   
    public long getStudentId() {
        return this.studentId;
    }
    
    public void setStudentId(long studentId) {
        this.studentId = studentId;
    }
    public long getLessonContentId() {
        return this.lessonContentId;
    }
    
    public void setLessonContentId(long lessonContentId) {
        this.lessonContentId = lessonContentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof StudentLessonAttendenceId) ) return false;
		 StudentLessonAttendenceId castOther = ( StudentLessonAttendenceId ) other; 
         
		 return (this.getStudentId()==castOther.getStudentId())
 && (this.getLessonContentId()==castOther.getLessonContentId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + (int) this.getStudentId();
         result = 37 * result + (int) this.getLessonContentId();
         return result;
   }   


}


