package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1

/**
 * StudentLessonAttendence generated by hbm2java
 */
public class StudentLessonAttendence implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private StudentLessonAttendenceId id;
	private LessonContent lessonContent;
	private StdStudent stdStudent;
	private Boolean attended;
	private String notes;

	public StudentLessonAttendence() {
	}

	public StudentLessonAttendence(StudentLessonAttendenceId id, LessonContent lessonContent, StdStudent stdStudent) {
		this.id = id;
		this.lessonContent = lessonContent;
		this.stdStudent = stdStudent;
	}

	public StudentLessonAttendence(StudentLessonAttendenceId id, LessonContent lessonContent, StdStudent stdStudent,
			Boolean attended, String notes) {
		this.id = id;
		this.lessonContent = lessonContent;
		this.stdStudent = stdStudent;
		this.attended = attended;
		this.notes = notes;
	}

	public StudentLessonAttendenceId getId() {
		return this.id;
	}

	public void setId(StudentLessonAttendenceId id) {
		this.id = id;
	}

	public LessonContent getLessonContent() {
		return this.lessonContent;
	}

	public void setLessonContent(LessonContent lessonContent) {
		this.lessonContent = lessonContent;
	}

	public StdStudent getStdStudent() {
		return this.stdStudent;
	}

	public void setStdStudent(StdStudent stdStudent) {
		this.stdStudent = stdStudent;
	}

	public Boolean getAttended() {
		return this.attended;
	}

	public void setAttended(Boolean attended) {
		this.attended = attended;
	}

	public String getNotes() {
		return this.notes;
	}

	public void setNotes(String notes) {
		this.notes = notes;
	}

}
