package Entities;
// Generated Sep 8, 2017 9:11:07 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * StudentLevelState generated by hbm2java
 */
public class StudentLevelState  implements java.io.Serializable {


     private StudentLevelStateId id;
     private Level level;
     private LevelStatus levelStatus;
     private StdStudent stdStudent;
     private Boolean active;
     private Date creationDate;
     private String createdBy;
     private Date lastModifiedDate;
     private String lastModifiedBy;

    public StudentLevelState() {
    }

	
    public StudentLevelState(StudentLevelStateId id, Level level, StdStudent stdStudent) {
        this.id = id;
        this.level = level;
        this.stdStudent = stdStudent;
    }
    public StudentLevelState(StudentLevelStateId id, Level level, LevelStatus levelStatus, StdStudent stdStudent, Boolean active, Date creationDate, String createdBy, Date lastModifiedDate, String lastModifiedBy) {
       this.id = id;
       this.level = level;
       this.levelStatus = levelStatus;
       this.stdStudent = stdStudent;
       this.active = active;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastModifiedDate = lastModifiedDate;
       this.lastModifiedBy = lastModifiedBy;
    }
   
    public StudentLevelStateId getId() {
        return this.id;
    }
    
    public void setId(StudentLevelStateId id) {
        this.id = id;
    }
    public Level getLevel() {
        return this.level;
    }
    
    public void setLevel(Level level) {
        this.level = level;
    }
    public LevelStatus getLevelStatus() {
        return this.levelStatus;
    }
    
    public void setLevelStatus(LevelStatus levelStatus) {
        this.levelStatus = levelStatus;
    }
    public StdStudent getStdStudent() {
        return this.stdStudent;
    }
    
    public void setStdStudent(StdStudent stdStudent) {
        this.stdStudent = stdStudent;
    }
    public Boolean getActive() {
        return this.active;
    }
    
    public void setActive(Boolean active) {
        this.active = active;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }




}


