package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1



/**
 * TeacherLessonContent generated by hbm2java
 */
public class TeacherLessonContent  implements java.io.Serializable {


     private TeacherLessonContentId id;
     private LessonContent lessonContent;
     private Teacher teacher;

    public TeacherLessonContent() {
    }

	
    public TeacherLessonContent(TeacherLessonContentId id) {
        this.id = id;
    }
    public TeacherLessonContent(TeacherLessonContentId id, LessonContent lessonContent, Teacher teacher) {
       this.id = id;
       this.lessonContent = lessonContent;
       this.teacher = teacher;
    }
   
    public TeacherLessonContentId getId() {
        return this.id;
    }
    
    public void setId(TeacherLessonContentId id) {
        this.id = id;
    }
    public LessonContent getLessonContent() {
        return this.lessonContent;
    }
    
    public void setLessonContent(LessonContent lessonContent) {
        this.lessonContent = lessonContent;
    }
    public Teacher getTeacher() {
        return this.teacher;
    }
    
    public void setTeacher(Teacher teacher) {
        this.teacher = teacher;
    }




}


