package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1



/**
 * TeacherLessonContentId generated by hbm2java
 */
public class TeacherLessonContentId  implements java.io.Serializable {


     private Long teacherId;
     private Long lessonContentId;

    public TeacherLessonContentId() {
    }

    public TeacherLessonContentId(Long teacherId, Long lessonContentId) {
       this.teacherId = teacherId;
       this.lessonContentId = lessonContentId;
    }
   
    public Long getTeacherId() {
        return this.teacherId;
    }
    
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }
    public Long getLessonContentId() {
        return this.lessonContentId;
    }
    
    public void setLessonContentId(Long lessonContentId) {
        this.lessonContentId = lessonContentId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TeacherLessonContentId) ) return false;
		 TeacherLessonContentId castOther = ( TeacherLessonContentId ) other; 
         
		 return ( (this.getTeacherId()==castOther.getTeacherId()) || ( this.getTeacherId()!=null && castOther.getTeacherId()!=null && this.getTeacherId().equals(castOther.getTeacherId()) ) )
 && ( (this.getLessonContentId()==castOther.getLessonContentId()) || ( this.getLessonContentId()!=null && castOther.getLessonContentId()!=null && this.getLessonContentId().equals(castOther.getLessonContentId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getTeacherId() == null ? 0 : this.getTeacherId().hashCode() );
         result = 37 * result + ( getLessonContentId() == null ? 0 : this.getLessonContentId().hashCode() );
         return result;
   }   


}


