package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Term generated by hbm2java
 */
public class Term  implements AbstractEntity, Serializable {


     private long termId;
     private Year year;
     private String code;
     private String name;
     private Date startDate;
     private Date endDate;
     private Date creationDate;
     private String createdBy;
     private Date lastModifiedDate;
     private String lastModifiedBy;
     private Set stdStudents = new HashSet(0);
     private Set lessons = new HashSet(0);

    public Term() {
    }

	
    public Term(long termId, Year year) {
        this.termId = termId;
        this.year = year;
    }
    public Term(long termId, Year year, String code, String name, Date startDate, Date endDate, Date creationDate, String createdBy, Date lastModifiedDate, String lastModifiedBy, Set stdStudents, Set lessons) {
       this.termId = termId;
       this.year = year;
       this.code = code;
       this.name = name;
       this.startDate = startDate;
       this.endDate = endDate;
       this.creationDate = creationDate;
       this.createdBy = createdBy;
       this.lastModifiedDate = lastModifiedDate;
       this.lastModifiedBy = lastModifiedBy;
       this.stdStudents = stdStudents;
       this.lessons = lessons;
    }
   
    public long getTermId() {
        return this.termId;
    }
    
    public void setTermId(long termId) {
        this.termId = termId;
    }
    public Year getYear() {
        return this.year;
    }
    
    public void setYear(Year year) {
        this.year = year;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public Date getCreationDate() {
        return this.creationDate;
    }
    
    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }
    public String getCreatedBy() {
        return this.createdBy;
    }
    
    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }
    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }
    
    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }
    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }
    
    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }
    public Set getStdStudents() {
        return this.stdStudents;
    }
    
    public void setStdStudents(Set stdStudents) {
        this.stdStudents = stdStudents;
    }
    public Set getLessons() {
        return this.lessons;
    }
    
    public void setLessons(Set lessons) {
        this.lessons = lessons;
    }




}


