package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UsrRole generated by hbm2java
 */
public class UsrRole  implements java.io.Serializable {


     private long roleId;
     private String code;
     private String name;
     private Set usrSubscriberRoles = new HashSet(0);
     private Set setRolesNotifications = new HashSet(0);

    public UsrRole() {
    }

	
    public UsrRole(long roleId) {
        this.roleId = roleId;
    }
    public UsrRole(long roleId, String code, String name, Set usrSubscriberRoles, Set setRolesNotifications) {
       this.roleId = roleId;
       this.code = code;
       this.name = name;
       this.usrSubscriberRoles = usrSubscriberRoles;
       this.setRolesNotifications = setRolesNotifications;
    }
   
    public long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(long roleId) {
        this.roleId = roleId;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getUsrSubscriberRoles() {
        return this.usrSubscriberRoles;
    }
    
    public void setUsrSubscriberRoles(Set usrSubscriberRoles) {
        this.usrSubscriberRoles = usrSubscriberRoles;
    }
    public Set getSetRolesNotifications() {
        return this.setRolesNotifications;
    }
    
    public void setSetRolesNotifications(Set setRolesNotifications) {
        this.setRolesNotifications = setRolesNotifications;
    }




}


