package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1



/**
 * UsrSubscriberRoleId generated by hbm2java
 */
public class UsrSubscriberRoleId  implements java.io.Serializable {


     private Long subscriberId;
     private Long roleId;

    public UsrSubscriberRoleId() {
    }

    public UsrSubscriberRoleId(Long subscriberId, Long roleId) {
       this.subscriberId = subscriberId;
       this.roleId = roleId;
    }
   
    public Long getSubscriberId() {
        return this.subscriberId;
    }
    
    public void setSubscriberId(Long subscriberId) {
        this.subscriberId = subscriberId;
    }
    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UsrSubscriberRoleId) ) return false;
		 UsrSubscriberRoleId castOther = ( UsrSubscriberRoleId ) other; 
         
		 return ( (this.getSubscriberId()==castOther.getSubscriberId()) || ( this.getSubscriberId()!=null && castOther.getSubscriberId()!=null && this.getSubscriberId().equals(castOther.getSubscriberId()) ) )
 && ( (this.getRoleId()==castOther.getRoleId()) || ( this.getRoleId()!=null && castOther.getRoleId()!=null && this.getRoleId().equals(castOther.getRoleId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSubscriberId() == null ? 0 : this.getSubscriberId().hashCode() );
         result = 37 * result + ( getRoleId() == null ? 0 : this.getRoleId().hashCode() );
         return result;
   }   


}


