package Entities;
// Generated Oct 5, 2017 11:18:29 AM by Hibernate Tools 4.3.1


import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;

/**
 * UsrSubscriber generated by hbm2java
 */
public class UsrSubscriber  implements AbstractEntity , Serializable {


     private long subscriberId;
     private StdStudent stdStudent;
     private String code;
     private String name;
     private String password;
     private Set usrSubscriberRoles = new HashSet(0);

    public UsrSubscriber() {
    }

	
    public UsrSubscriber(long subscriberId) {
        this.subscriberId = subscriberId;
    }
    public UsrSubscriber(long subscriberId, StdStudent stdStudent, String code, String name, String password, Set usrSubscriberRoles) {
       this.subscriberId = subscriberId;
       this.stdStudent = stdStudent;
       this.code = code;
       this.name = name;
       this.password = password;
       this.usrSubscriberRoles = usrSubscriberRoles;
    }
   
    public long getSubscriberId() {
        return this.subscriberId;
    }
    
    public void setSubscriberId(long subscriberId) {
        this.subscriberId = subscriberId;
    }
    public StdStudent getStdStudent() {
        return this.stdStudent;
    }
    
    public void setStdStudent(StdStudent stdStudent) {
        this.stdStudent = stdStudent;
    }
    public String getCode() {
        return this.code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Set getUsrSubscriberRoles() {
        return this.usrSubscriberRoles;
    }
    
    public void setUsrSubscriberRoles(Set usrSubscriberRoles) {
        this.usrSubscriberRoles = usrSubscriberRoles;
    }




}


