package Entities;
// Generated Sep 29, 2017 12:28:05 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Year generated by hbm2java
 */
public class Year implements AbstractEntity, Serializable {

    private long yearId;
    private Term term;
    private String code;
    private String name;
    private Date startDate;
    private Date endDate;
    private Date creationDate;
    private String createdBy;
    private Date lastModifiedDate;
    private String lastModifiedBy;
    private Set stdStudents = new HashSet(0);
    private Set lessons = new HashSet(0);

    public Year() {
    }

    public Year(long yearId, Term term) {
        this.yearId = yearId;
        this.term = term;
    }

    public Year(long yearId, Term term, String code, String name, Date startDate, Date endDate, Date creationDate, String createdBy, Date lastModifiedDate, String lastModifiedBy, Set stdStudents, Set lessons) {
        this.yearId = yearId;
        this.term = term;
        this.code = code;
        this.name = name;
        this.startDate = startDate;
        this.endDate = endDate;
        this.creationDate = creationDate;
        this.createdBy = createdBy;
        this.lastModifiedDate = lastModifiedDate;
        this.lastModifiedBy = lastModifiedBy;
        this.stdStudents = stdStudents;
        this.lessons = lessons;
    }

    public long getYearId() {
        return this.yearId;
    }

    public void setYearId(long yearId) {
        this.yearId = yearId;
    }

    public Term getTerm() {
        return this.term;
    }

    public void setTerm(Term term) {
        this.term = term;
    }

    public String getCode() {
        return this.code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getStartDate() {
        return this.startDate;
    }

    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    public Date getEndDate() {
        return this.endDate;
    }

    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }

    public Date getCreationDate() {
        return this.creationDate;
    }

    public void setCreationDate(Date creationDate) {
        this.creationDate = creationDate;
    }

    public String getCreatedBy() {
        return this.createdBy;
    }

    public void setCreatedBy(String createdBy) {
        this.createdBy = createdBy;
    }

    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Set getStdStudents() {
        return this.stdStudents;
    }

    public void setStdStudents(Set stdStudents) {
        this.stdStudents = stdStudents;
    }

    public Set getLessons() {
        return this.lessons;
    }

    public void setLessons(Set lessons) {
        this.lessons = lessons;
    }

}
